"""
email_flavour.py
----------------
The 'human' bits of the audit completion email: a friendly opener, a real
quote of the day, and a true 'on this day' fun fact.

HARD RULE (same as the decks): never confidently wrong. Every quote and every
historical fact in here has been hand-checked. Nothing is generated by GPT at
send time, because a hallucinated 'on this day in 1722...' would be exactly the
kind of confidently-wrong claim the rest of this tool works hard to avoid.

Selection is seeded by the date, so the "quote of the day" is the same for the
whole team on a given day, while the jokey opener varies per audit run.
"""

import random


# ── Friendly openers (the comedy lives here, not in the quotes) ────────────────
# {client} is filled in. Keep it warm, light, British, and never at the client's
# expense. No em-dashes (house style).
_OPENERS = [
    "Right, that's {client} all audited. Kettle's back on.",
    "Done. I've just finished rummaging through {client}'s Google Ads account so you don't have to.",
    "Audit finished for {client}. I went through it line by line, no biscuits were harmed.",
    "All done on {client}. I had a good poke about and made some notes for you.",
    "That's {client} wrapped. I read every campaign so your eyes don't have to glaze over.",
    "Finished auditing {client}. I even checked the boring bits twice.",
    "{client} is audited and ready. I did the digging, you get the credit.",
    "Job done on {client}. I've laid it all out like a story so it's an easy read.",
]

# A light line about the effort, given the duration string and token count.
_EFFORT_LINES = [
    "It took me {duration} and {tokens} tokens of hard thinking.",
    "{duration} of work and {tokens} tokens later, here we are.",
    "I spent {duration} on it and burned through {tokens} tokens, which I'm told is a respectable lunch.",
    "Time on the clock: {duration}. Tokens spent: {tokens}. Coffee consumed: classified.",
]


# ── Token jest of the day ──────────────────────────────────────────────────────
# A silly 'what does N tokens even mean' line. NOTE: these are jokes, not facts.
# The numbers are all computed from the real token count, so they are internally
# correct (66m of stacked coins really is ~22 storeys), but the framing is daft on
# purpose. This is the one place daftness is allowed; the quote and 'on this day'
# fact next to it stay strictly true.
def _token_jests(t):
    # All numbers are computed from the real token count, so they are internally
    # correct (the daftness is in the framing, not the maths).
    coins_m    = round(t * 2.8 / 1000)        # a £1 coin is 2.8mm thick
    storeys    = max(1, round(coins_m / 3))   # ~3m a storey
    coins_kg   = round(t * 8.75 / 1000)       # a £1 coin weighs 8.75g
    hours      = round(t / 3600, 1)           # if each token were a second
    pages      = max(1, round(t / 250))       # ~250 words a paperback page
    buses      = max(1, round(t / 2000))      # pure nonsense, scales with t
    reams      = max(1, round(t / 500))       # 500 sheets a ream
    paper_m    = round(t / 10000, 1)          # A4 is ~0.1mm thick
    read_min   = max(1, round(t / 200))       # ~200 words a minute reading
    type_hr    = round(t / 40 / 60, 1)        # typing at ~40 words a minute
    novel_pct  = max(1, round(t / 90000 * 100))  # a novel is ~90,000 words
    walk_km    = round(t * 0.75 / 1000, 1)    # ~0.75m a stride
    cups       = max(1, round(t / 500))
    biscuits   = max(1, round(t / 250))
    pennies    = round(t / 100)               # £ if each token cost a penny
    laps       = max(1, round(t / 1500))
    return [
        f"Stacked as £1 coins, that's a tower about {coins_m}m high, roughly a "
        f"{storeys}-storey building, and yes, £{t:,} in real money, which feels steep for one audit.",
        f"If each token were a second, I'd have been thinking out loud for about {hours} hours.",
        f"That's roughly a {pages}-page paperback's worth of words, and I read every one so you don't have to.",
        f"Converted to mice, that's enough to fill about {buses} double-decker buses, "
        f"assuming the mice sit still, which they never do.",
        f"As £1 coins those would weigh about {coins_kg}kg, so maybe don't carry them all to the bank at once.",
        f"Laid end to end, all {t:,} tokens would stretch from the desk to the kettle and back several times.",
        f"Printed out, that's about {reams} reams of paper, a stack roughly {paper_m}m high. Spare a thought for the tree.",
        f"At a comfy reading pace, {t:,} words would take you about {read_min} minutes, and I did it in a blink.",
        f"If I'd typed it by hand at office speed, that's about {type_hr} hours of two-finger tapping.",
        f"That's roughly {novel_pct}% of the way to writing an actual novel, plot not included.",
        f"If each token were a footstep, that's about {walk_km}km of pacing, basically a thinking-person's hike.",
        f"Measured the British way, that's about {cups} cups of tea worth of effort.",
        f"Converted to biscuits, that's about {biscuits} biscuits, which is a strong argument for a bigger tin.",
        f"At a penny a token this audit cost me roughly £{pennies} in entirely imaginary money.",
        f"That's about {laps} laps of the office, give or take a desk and a wrong turn by the printer.",
        f"If each token were a domino, the topple would be long, loud and deeply satisfying.",
        f"Enough tokens to wallpaper a small downstairs loo, probably, if tokens came in rolls.",
        f"If tokens were Lego bricks, standing on this lot would be a proper health-and-safety incident.",
        f"That's a small, faintly underwhelming galaxy of tokens, all pointed at your Google Ads account.",
        f"Roughly {t:,} tokens, or as I like to call it, one (1) very thorough read of your account.",
        f"If each token were a raindrop, that's a respectable drizzle, classic British weather.",
        f"Stacked as Jaffa Cakes (a cake, legally) that's a tower nobody would leave standing for long.",
        f"That's about {hours} hours of thinking if a token were a second, and you doing something far nicer.",
        f"Enough tokens to bore a teenager senseless, and yet here they are, hard at work.",
        f"If I got 10p for every token, I'd have knocked off early and bought everyone lunch.",
        f"That's {t:,} tiny decisions, all so you don't have to squint at a spreadsheet on a Monday.",
    ]


def token_jest(today, client_name, cid, tokens_used):
    """A daft, count-scaled one-liner about the tokens used. Returns '' if we
    never captured a token count (nothing funny to say about zero)."""
    if not tokens_used:
        return ""
    rng = _run_rng(today, client_name, cid)
    return rng.choice(_token_jests(tokens_used))


# ── Quote of the day (all real, all checked) ───────────────────────────────────
# (quote, who said it). No em-dashes inside the quotes (house style); where the
# original used one, a comma or full stop has been used instead.
_QUOTES = [
    ("Half the money I spend on advertising is wasted; the trouble is I don't know which half.", "John Wanamaker"),
    ("Without data, you're just another person with an opinion.", "W. Edwards Deming"),
    ("Data is the new oil.", "Clive Humby"),
    ("The aim of marketing is to know and understand the customer so well the product fits and sells itself.", "Peter Drucker"),
    ("People don't buy what you do; they buy why you do it.", "Simon Sinek"),
    ("Content is king.", "Bill Gates"),
    ("Your most unhappy customers are your greatest source of learning.", "Bill Gates"),
    ("Innovation distinguishes between a leader and a follower.", "Steve Jobs"),
    ("Make it simple. Make it memorable. Make it inviting to look at.", "Leo Burnett"),
    ("The best way to predict the future is to invent it.", "Alan Kay"),
    ("Stopping advertising to save money is like stopping your watch to save time.", "Henry Ford"),
    ("Marketing is no longer about the stuff you make, but the stories you tell.", "Seth Godin"),
]


# ── On this day (verified true). Keyed by MM-DD. ───────────────────────────────
# Only assert a dated fact when we have a checked entry for that exact calendar
# day; otherwise we fall back to a general fun fact, so we never make up a date.
_ON_THIS_DAY = {
    "01-01": (1660, "Samuel Pepys began writing his famous diary."),
    "02-14": (1876, "Alexander Graham Bell filed his patent for the telephone."),
    "03-10": (1876, "Alexander Graham Bell made the first ever phone call: 'Mr Watson, come here.'"),
    "04-12": (1961, "Yuri Gagarin became the first human in space."),
    "05-25": (1977, "the first Star Wars film opened in cinemas."),
    "06-16": (1963, "Valentina Tereshkova became the first woman in space, aboard Vostok 6."),
    "06-23": (1912, "Alan Turing, the father of modern computing, was born."),
    "07-20": (1969, "Apollo 11 landed the first humans on the Moon."),
    "08-06": (1991, "the world's first website went live, built by Tim Berners-Lee."),
    "09-09": (1947, "engineers logged a real moth stuck in a computer, giving us the word 'bug'."),
    "10-23": (2001, "Apple unveiled the very first iPod."),
    "11-09": (1989, "the Berlin Wall began to fall."),
}

# General fun facts (verified true), used when today has no dated entry.
_GENERAL_FACTS = [
    "Google was originally called 'BackRub' before its founders settled on the name we know today.",
    "Wi-Fi doesn't actually stand for anything. It's just a catchy brand name, not 'Wireless Fidelity'.",
    "Google AdWords launched in October 2000 with around 350 advertisers. Today there are millions.",
    "Honey never spoils. Sealed pots found in ancient Egyptian tombs were still edible thousands of years on.",
    "A group of flamingos is called a 'flamboyance'.",
    "Octopuses have three hearts and blue blood.",
    "Bananas are berries, but strawberries technically are not.",
    "The Eiffel Tower can grow more than 15cm taller in summer, as the iron expands in the heat.",
]


def _daily_rng(today):
    """Same pick all day (a genuine 'of the day'), changes day to day."""
    return random.Random(today.toordinal())


def _run_rng(today, client_name, cid):
    """Varies per audit run, so two audits on the same day feel fresh."""
    return random.Random(f"{today.toordinal()}|{client_name}|{cid}")


def opener_line(today, client_name, cid):
    rng = _run_rng(today, client_name, cid)
    return rng.choice(_OPENERS).format(client=client_name)


def effort_line(today, client_name, cid, duration_str, tokens_used):
    rng = _run_rng(today, client_name, cid)
    tok = f"{tokens_used:,}" if tokens_used else "a handful of"
    return rng.choice(_EFFORT_LINES).format(duration=duration_str, tokens=tok)


def quote_of_the_day(today):
    quote, who = _daily_rng(today).choice(_QUOTES)
    return quote, who


def fun_fact_of_the_day(today):
    """Returns a true fact. Prefers a dated 'on this day' line for today's date,
    else a general fun fact. Never invents a date."""
    key = today.strftime("%m-%d")
    if key in _ON_THIS_DAY:
        year, event = _ON_THIS_DAY[key]
        return f"On this day in {year}, {event}"
    return _daily_rng(today).choice(_GENERAL_FACTS)
